### ISSUE TITLE
manually copy over `classification/models` from `CoastSat` 

### ISSUE THREAD

**Issue by dbuscombe-usgs** [dbuscombe-usgs/CoastSeg#65]
Using `main` https://github.com/2320sharon/CoastSeg/commit/fc61aa7247e52f5b41f65ef28bc98e06cc399f29, in order to use `extract_shorelines_from_rois` in `satellite_derived_shorelines.ipynb`, you need to manually copy over `classification/models` from `CoastSat` 

It is inconvenient and a novice user would not know to do this, so we should come up with a strategy for packaging up the classification models. These are `.pkl` files that carry out the image segmentation in CoastSat

**Comment by 2320sharon** [comment]
Oh, I didn't know that the user had to copy over the classification models manually. I'll do some research and find the best way to package the models up. Thanks for finding this bug!

**Comment by 2320sharon** [comment]
The classification models from CoastSat are no longer ignored in the `.gittignore` file and the models have been added to CoastSeg's main branch on my fork
